name: Perform a Release

on:
  workflow_dispatch:
    inputs:
      npm-version-arg:
        description: Argument to npm-version
        default: minor
        required: true

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    outputs:
      tag: ${{ steps.release_info.outputs.tag }}
    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Configure git
        run: |
          git config user.name 'Release Action'
          git config user.email '<>'

      - uses: actions/setup-node@v1
        with:
          node-version: "12"

      - name: Update package version
        id: update-package-version
        run: |
          VERSION=$(npm version "${{ github.event.inputs.npm-version-arg }}")
          echo "::set-output name=version::$VERSION"

      - name: Push new version
        run: git push

      - name: Perform npm tasks
        run: npm run ci

      - name: Commit to release branch
        id: release_info
        run: |
          TAG="v${{ steps.update-package-version.outputs.version }}"
          BRANCH="release/$TAG"
          git switch -c $BRANCH
          git add --force dist lib

          MESSAGE="Build for $(git rev-parse --short HEAD)"
          git commit --allow-empty -m "$MESSAGE"
          git tag -a -m "Release $TAG" $TAG
          git push origin $TAG

          echo "::set-output name=tag::$TAG"

  release:
    name: Release
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Create Release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ needs.build.outputs.tag }}
          release_name: Release ${{ needs.build.outputs.tag }}
          draft: false
          prerelease: false
